name: Publish to NPMJS and GPR

on:
    push:
        branches:
            - master

# on:
#     release:
#         types: [created]

jobs:
    build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v1
          with:
              node-version: 12
        - run: npm ci
        - run: npm run build
        - run: npm run lint

    # Publish to NPMJS
    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    # Publish to GitHub Package Registry
    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  scope: "@abhimanusharma"
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}
