name: Publish to NPMJS and GPR

on:
    push:
        branches:
            - master

# on:
#     release:
#         types: [created]

jobs:
    publish-to-npm-and-gpr:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo
            - uses: actions/checkout@master

            # Update package version and set up git
            - uses: actions/setup-node@master
            - name: Update package version and setup git
              run: |
                  git config user.name "abhimanusharma"
                  git config user.email dragonabv1@github.com
                  npm version 1.0.$(date +%s)

    # Publish to NPMJS
    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    # Publish to GitHub Package Registry
    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  scope: "@abhimanusharma"
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}
